// apps/hydrate-framework/src/solid-components/ui/heading.solid.tsx
/** @jsxImportSource solid-js */
import { type JSX, type ParentProps, splitProps } from "solid-js";
import { cx } from "../../../styled-system/css";
import {
  type TextVariantProps,
  text,
} from "../../../styled-system/recipes/text";

interface TextProps
  extends JSX.HTMLAttributes<HTMLHeadingElement>,
    TextVariantProps {
  as?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
}

const Heading = (props: ParentProps<TextProps>) => {
  const [headingProps, parentChild, rest] = splitProps(
    props,
    ["as", "variant", "size", "class"],
    ["children"],
  );

  if (headingProps.as === "h2") {
    return (
      <h2
        class={cx(
          text({ size: headingProps.size, variant: headingProps.variant }),
          headingProps.class,
        )}
        {...rest}
      >
        {parentChild.children}
      </h2>
    );
  }

  if (headingProps.as === "h3") {
    return (
      <h3
        class={cx(
          text({ size: headingProps.size, variant: headingProps.variant }),
          headingProps.class,
        )}
        {...rest}
      >
        {parentChild.children}
      </h3>
    );
  }

  if (headingProps.as === "h4") {
    return (
      <h4
        class={cx(
          text({ size: headingProps.size, variant: headingProps.variant }),
          headingProps.class,
        )}
        {...rest}
      >
        {parentChild.children}
      </h4>
    );
  }

  if (headingProps.as === "h5") {
    return (
      <h5
        class={cx(
          text({ size: headingProps.size, variant: headingProps.variant }),
          headingProps.class,
        )}
        {...rest}
      >
        {parentChild.children}
      </h5>
    );
  }

  if (headingProps.as === "h6") {
    return (
      <h6
        class={cx(
          text({ size: headingProps.size, variant: headingProps.variant }),
          headingProps.class,
        )}
        {...rest}
      >
        {parentChild.children}
      </h6>
    );
  }

  return (
    <h1
      class={cx(
        text({ size: headingProps.size, variant: headingProps.variant }),
        headingProps.class,
      )}
      {...rest}
    >
      {parentChild.children}
    </h1>
  );
};

export default Heading;

// apps/hydrate-framework/src/svelte-components/ui/heading.svelte
<script lang="ts">
  import type { HTMLAttributes } from 'svelte/elements';
  import { cx } from '../../../styled-system/css';
  import { type TextVariantProps, text } from '../../../styled-system/recipes/text';

  interface HeadingProps extends HTMLAttributes<HTMLHeadElement>, TextVariantProps {
    as?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
    class?: string;
  }

  const {
    children,
    variant = 'heading',
    size,
    class: className,
    as = 'h1',
    ...props
  }: HeadingProps = $props();
</script>

{#if as === 'h1'}
  <h1 class={cx(text({ variant, size }), className)} {...props}>{@render children?.()}</h1>
{:else if as === 'h2'}
  <h2 class={cx(text({ variant, size }), className)} {...props}>{@render children?.()}</h2>
{:else if as === 'h3'}
  <h3 class={cx(text({ variant, size }), className)} {...props}>{@render children?.()}</h3>
{:else if as === 'h4'}
  <h4 class={cx(text({ variant, size }), className)} {...props}>{@render children?.()}</h4>
{:else if as === 'h5'}
  <h5 class={cx(text({ variant, size }), className)} {...props}>{@render children?.()}</h5>
{:else if as === 'h6'}
  <h6 class={cx(text({ variant, size }), className)} {...props}>{@render children?.()}</h6>
{/if}
