// apps/hydrate-framework/src/solid-components/ui/text.solid.tsx
/** @jsxImportSource solid-js */
import { type JSX, type ParentProps, splitProps } from "solid-js";
import { cx } from "../../../styled-system/css";
import {
  type TextVariantProps,
  text,
} from "../../../styled-system/recipes/text";

interface TextProps
  extends JSX.HTMLAttributes<HTMLParagraphElement>,
    TextVariantProps {}

const Text = (props: ParentProps<TextProps>) => {
  const [textProps, parentChild, rest] = splitProps(
    props,
    ["variant", "size", "class"],
    ["children"],
  );
  return (
    <p
      class={cx(
        text({ size: textProps.size, variant: textProps.variant }),
        textProps.class,
      )}
      {...rest}
    >
      {parentChild.children}
    </p>
  );
};

export default Text;

// apps/hydrate-framework/src/svelte-components/ui/text.svelte
<script lang="ts">
  import type { HTMLAttributes } from 'svelte/elements';
  import { cx } from '../../../styled-system/css';
  import { type TextVariantProps, text } from '../../../styled-system/recipes/text';

  interface TextProps extends HTMLAttributes<HTMLParagraphElement>, TextVariantProps {
    class?: string;
  }

  const { children, variant, size, class: className, ...props }: TextProps = $props();
</script>

<p class={cx(text({ variant, size }), className)} {...props}>{@render children?.()}</p>
